// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Ads: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/organism/Ads.vue')['default']
    Alert: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/atom/Alert.vue')['default']
    BaseButton: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/atom/BaseButton.vue')['default']
    Footer: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/organism/Footer.vue')['default']
    FormURL: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/molecules/FormURL.vue')['default']
    FromFile: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/molecules/FromFile.vue')['default']
    GetApp: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/atom/GetApp.vue')['default']
    Header: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/organism/Header.vue')['default']
    HrefButton: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/atom/HrefButton.vue')['default']
    IconArrow: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/icons/IconArrow.vue')['default']
    IconArrow2: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/icons/IconArrow2.vue')['default']
    IconCheck: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/icons/IconCheck.vue')['default']
    IconCoffe: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/icons/IconCoffe.vue')['default']
    IconDownload: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/icons/IconDownload.vue')['default']
    IconGear: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/icons/IconGear.vue')['default']
    IconLongArrow: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/icons/IconLongArrow.vue')['default']
    IconStar: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/icons/IconStar.vue')['default']
    IconUpload: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/icons/IconUpload.vue')['default']
    IconUrl: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/icons/IconUrl.vue')['default']
    Main: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/organism/Main.vue')['default']
    MainResult: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/organism/MainResult.vue')['default']
    ReloadPrompt: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/atom/ReloadPrompt.vue')['default']
    Sample: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/organism/Sample.vue')['default']
    TabButton: typeof import('D:/HartD/Programing/Web Project/wibux2-app/wibux2/src/components/atom/TabButton.vue')['default']
  }
}

export { }
